//! TextMate grammar snapshot tests.
//!
//! Requires Node.js. Snapshots are generated by:
//!   cd syntax-highlighting/textmate && npm install
//!   node tokenize.js test/inputs/simple_struct.vale > test/snapshots/simple_struct.txt
//!   # ... repeat for each input file
//!
//! Run with:
//!   cargo test -- --ignored textmate

use std::path::PathBuf;
use std::process::Command;

fn textmate_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../syntax-highlighting/textmate")
}

fn run_snapshot_test(input_name: &str, snapshot_name: &str) {
    let dir = textmate_dir();
    let input_path = dir.join("test/inputs").join(input_name);
    let snapshot_path = dir.join("test/snapshots").join(snapshot_name);

    let output = Command::new("node")
        .arg(dir.join("tokenize.js"))
        .arg(&input_path)
        .current_dir(&dir)
        .output()
        .expect("Failed to run tokenize.js — is Node.js installed? Run: cd syntax-highlighting/textmate && npm install");

    assert!(
        output.status.success(),
        "tokenize.js failed for {}:\nstdout: {}\nstderr: {}",
        input_name,
        String::from_utf8_lossy(&output.stdout),
        String::from_utf8_lossy(&output.stderr),
    );

    let actual = String::from_utf8(output.stdout).unwrap();

    let expected = std::fs::read_to_string(&snapshot_path).unwrap_or_else(|e| {
        panic!(
            "Missing snapshot '{}': {}\nGenerate it with:\n  cd syntax-highlighting/textmate && npm install\n  node tokenize.js test/inputs/{} > test/snapshots/{}",
            snapshot_path.display(),
            e,
            input_name,
            snapshot_name,
        )
    });

    assert_eq!(
        actual.trim(),
        expected.trim(),
        "TextMate snapshot mismatch for {}\nRun `node tokenize.js test/inputs/{} > test/snapshots/{}` to update.",
        input_name,
        input_name,
        snapshot_name,
    );
}

macro_rules! textmate_snapshot_test {
    ($name:ident, $input:literal, $snapshot:literal) => {
        #[test]
        #[ignore = "Requires Node.js and npm install. Run: cargo test -- --ignored"]
        fn $name() {
            run_snapshot_test($input, $snapshot);
        }
    };
}

textmate_snapshot_test!(tm_simple_struct,    "simple_struct.vale",    "simple_struct.txt");
textmate_snapshot_test!(tm_function_def,     "function_def.vale",     "function_def.txt");
textmate_snapshot_test!(tm_string_interp,    "string_interp.vale",    "string_interp.txt");
textmate_snapshot_test!(tm_comments,         "comments.vale",         "comments.txt");
textmate_snapshot_test!(tm_generics,         "generics.vale",         "generics.txt");
textmate_snapshot_test!(tm_control_flow,     "control_flow.vale",     "control_flow.txt");
textmate_snapshot_test!(tm_ownership,        "ownership.vale",        "ownership.txt");
textmate_snapshot_test!(tm_attributes,       "attributes.vale",       "attributes.txt");
textmate_snapshot_test!(tm_operators,        "operators.vale",        "operators.txt");
textmate_snapshot_test!(tm_lambdas,          "lambdas.vale",          "lambdas.txt");
textmate_snapshot_test!(tm_complete_program, "complete_program.vale", "complete_program.txt");
